UWTextbookExchange/config/routes.rb
Rails.application.routes.draw do  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup'}
  devise_scope :user do
    get 'resend', :to => 'devise/confirmations#new'
    get 'passreset', :to => 'devise/passwords#new'
    get 'unlockresend', :to=> 'devise/unlocks#new'
  end

  resources :messages

  root :to => "init#index"

  match 'find', to: 'get_book#find', :via => [:get, :post]
  match 'show', to: 'get_book#show', :via => [:get]
  match 'post', to: 'get_book#post', :via => [:get]
  match 'postto', to: 'get_book#postto', :via => [:get] 
 
  match 'personal', to: 'init#personal', :via => [:get]
  match 'showcount', to: 'init#showcount', :via => [:get]
  match 'showstatus', to: 'init#showstatus', :via => [:get]
  match 'chat', to: 'init#chat', :via => [:get]
  match 'chatlist', to: 'init#chatlist', :via => [:get]
  match 'terms', to: 'init#terms', :via => [:get]
  match 'traded', to: 'init#traded', :via => [:get]
  match 'unlist', to: 'init#unlist', :via => [:get]
  match 'resume', to: 'init#resume', :via => [:get]
  match 'delete', to: 'init#delete', :via => [:get]
  match 'newbook', to: 'init#newbook', :via => [:get]
  match 'addnew', to: 'init#addnew', :via => [:post]

  match 'markread', to: 'messages#markread', :via => [:get]
  match 'getmessage', to: 'messages#getmessage', :via => [:get]
  match 'subscribe', to: 'messages#subscribe', :via => [:get]

  match 'manage', to: 'manage#manage', :via => [:get]
  match 'overview', to: 'manage#overview', :via => [:get]
  match 'usermanage', to: 'manage#usermanage', :via => [:get]
  match 'userdetails', to: 'manage#userdetails', :via => [:get]
  match 'bookmanage', to: 'manage#bookmanage', :via => [:get]
  match 'bookedit', to: 'manage#bookedit', :via => [:get]
  match 'bookchangesave', to: 'manage#bookchangesave', :via => [:post]
  match 'reviewnew', to: 'manage#reviewnew', :via => [:get]
  match 'newdetails', to: 'manage#newdetails', :via => [:get]
  match 'passnew', to: 'manage#passnew', :via => [:post]

  match "*path", to: redirect("/"), via: :all
end

UWTextbookExchange/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UWTextbookExchange</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
</body>
</html>

UWTextbookExchange/app/views/layouts/bar.html.erb
<script type="text/javascript">
	$( document ).ready(function(){	
		$('[name=authenticity_token]').each(function(){this.value = "<%= form_authenticity_token.to_s %>"});
	});
<% if user_signed_in? %>
	var flashing = null
	$( document ).ready(function(){	
		updateCount();
		setInterval(updateCount,30000);
		if (<%= @msgc ? @msgc.unread : 0 %> > 0){
			flashing = setInterval(function(){ $("#chatmsg").fadeOut(300).fadeIn(300); },600);
		}
	});

	function updateCount(){
		$.ajax({
		url:  "/showcount",
		type: "GET",
		dataType: 'json',
		}).success(function(data){
			$("#msgct").html(data.count);
			if (data.count != 0){
				clearInterval(flashing);
				flashing = setInterval(function(){ $("#chatmsg").fadeOut(300).fadeIn(300); },600);
			} else {
				clearInterval(flashing);
			}
		});
	}
<% end %>
</script>
<style>
.login_info {
	padding: 10px;
	float:right;
}
#msgblock{
	float: left;
}
.main {
	margin-bottom: 65px !important;
}
.nav>li>a:hover, .nav>li>a:focus {
text-decoration: none;
background-color: #A9BEFF;
}
.navbar-toggle {
	margin-right: 20px;
}
.navbar-default .navbar-collapse, .navbar-default .navbar-form {
	background-color: orange;
}
.container-fluid {
	padding: 0px;
}


.navbar-fixed-top {
	border-width: 0 0 0px;
}

.navbar-header{
	background-color:transparent;
}
.navbar-header {
	background-color: orange;
}
.navbar-brand {
font-size: 24px;
margin-left: 0px !important;
}
.navbar-fixed-bottom a {
	color:orange;
}
.navbar-fixed-bottom{
	background-color:white;
	width:100%
}

.navbar-form .form-control {
	margin-bottom:0px;
}
</style>
<!-- Top Navigation Bar -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
	 		<a class="navbar-brand" href="/"><strong>Hustees</strong></a>
			<ul id="msgblock" class="nav">
			<% if user_signed_in? %>
				<li id="chatmsg" class="active"><a href="/chat" class="dif">Message(<span id='msgct'><%= @msgc ? @msgc.unread : 0 %></span>)</a></li>
			<% end %>
			</ul>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

			<!-- Preference Dropdown -->
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<% if user_signed_in? %>
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" style="float: right;">Preference <b class="caret"></b></a>
						<ul class="dropdown-menu">                
							<li><%= link_to('Personal Settings', 'personal') %></li>
							<li class="divider"></li>
							<% if current_user.admin %>
								<li><%= link_to "Admin Dashboard", 'manage' %></li>
								<li class="divider"></li>
							<% end %>
							<li><%= link_to('Logout', destroy_user_session_path) %></li>
						</ul>
					<% else %>
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" style="float: right;">More <b class="caret"></b></a>
						<ul class="dropdown-menu"> 
							<% if devise_mapping.registerable? && controller_name != 'registrations' %>
								<li><%= link_to "Sign up", new_registration_path(resource_name) %></li>
							<% end %>
							<% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
								<li><%= link_to "Forgot your password?", '/passreset' %></li>
							<% end %>

							<% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
								<li><%= link_to "Didn't receive confirmation instructions?", '/resend' %></li>
							<% end %>

							<% if devise_mapping.lockable? && controller_name != 'unlocks' %>
								<li><%= link_to "Didn't receive unlock instructions?", '/unlockresend' %></li>
							<% end %>
						</ul>
					<% end %>
				</li>
			</ul>
			<% if user_signed_in? %>
				<div class = "login_info">
					<%= current_user.username %>
				</div>
			<% end %>


			<!-- Login Form -->
			<% if !user_signed_in? %>
				<%= form_for(resource, as: resource_name, url: session_path(resource_name), html:{class: "navbar-form navbar-right", role: "form"}) do |f| %>
					<div class="form-group">
						<%= f.email_field :email, autofocus: true, placeholder: "Email", class: "form-control", id: "exampleInputEmail2"%>
					</div>

					<div class="form-group">
						<%= f.password_field :password,placeholder: "Password", autocomplete: "off", class: "form-control", id: "exampleInputPassword2" %>
					</div>

					<% if devise_mapping.rememberable? %>
						<div class="checkbox">
							<div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
						</div>
					<% end %>

					<%= f.submit "Sign in" , class: "btn-sm btn-default" %>
				<% end %>
			<% end %>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

UWTextbookExchange/app/views/layouts/foot.html.erb
	<footer>
			<div class="container navbar-fixed-bottom">
				<div class="row" style="text-align:center;padding-top: 5px;">
					<div class="col-lg-12">
						<ul class="list-inline">
							<li><a href="/"><strong>Home</strong></a>
							</li>
							<li class="footer-menu-divider">&sdot;</li>
							<li><a href="mailto:tebookglobal@gmail.com"><strong>Contact</strong></a>
							</li>
						</ul>
						<p class="copyright text-muted small"><strong>Copyright &copy; Hustees 2014. All Rights Reserved</strong></p>
					</div>
				</div>
			</div>
	</footer>