UWTextbookExchange/config/routes.rb
Rails.application.routes.draw do  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup'}
  devise_scope :user do
    get 'resend', :to => 'devise/confirmations#new'
    get 'passreset', :to => 'devise/passwords#new'
    get 'unlockresend', :to=> 'devise/unlocks#new'
  end

  resources :messages

  root :to => "init#index"

  match 'find', to: 'get_book#find', :via => [:get, :post]
  match 'show', to: 'get_book#show', :via => [:get]
  match 'post', to: 'get_book#post', :via => [:get]
  match 'postto', to: 'get_book#postto', :via => [:get] 
 
  match 'personal', to: 'init#personal', :via => [:get]
  match 'showcount', to: 'init#showcount', :via => [:get]
  match 'showstatus', to: 'init#showstatus', :via => [:get]
  match 'chat', to: 'init#chat', :via => [:get]
  match 'chatlist', to: 'init#chatlist', :via => [:get]
  match 'terms', to: 'init#terms', :via => [:get]
  match 'traded', to: 'init#traded', :via => [:get]
  match 'unlist', to: 'init#unlist', :via => [:get]
  match 'resume', to: 'init#resume', :via => [:get]
  match 'delete', to: 'init#delete', :via => [:get]
  match 'newbook', to: 'init#newbook', :via => [:get]
  match 'addnew', to: 'init#addnew', :via => [:post]

  match 'markread', to: 'messages#markread', :via => [:get]
  match 'getmessage', to: 'messages#getmessage', :via => [:get]
  match 'subscribe', to: 'messages#subscribe', :via => [:get]

  match 'manage', to: 'manage#manage', :via => [:get]
  match 'overview', to: 'manage#overview', :via => [:get]
  match 'usermanage', to: 'manage#usermanage', :via => [:get]
  match 'userdetails', to: 'manage#userdetails', :via => [:get]
  match 'bookmanage', to: 'manage#bookmanage', :via => [:get]
  match 'bookedit', to: 'manage#bookedit', :via => [:get]
  match 'bookchangesave', to: 'manage#bookchangesave', :via => [:post]
  match 'reviewnew', to: 'manage#reviewnew', :via => [:get]
  match 'newdetails', to: 'manage#newdetails', :via => [:get]
  match 'passnew', to: 'manage#passnew', :via => [:post]

  match "*path", to: redirect("/"), via: :all
end

UWTextbookExchange/app/controllers/get_book_controller.rb
class GetBookController < ApplicationController
 layout false 
 before_filter :authenticate_user!, :except => [:find, :show]
  def find
	if params["coursename"].present? && !params["coursename"].blank?
		@course = Course.where(:course_name => params[:coursename].strip.upcase).first
		if !@course
		  flash[:notice] = "This course is not held in this quarter, or misspell anything?"
		  return redirect_to(root_url)
		end
	elsif params[:course].present? && !params[:course].blank?
		session[:last_dep] = params[:course]["department"].strip
		session[:last_class] = params[:course]["class"].strip
		courseName = params[:course]["department"].strip.upcase + params[:course]["class"].strip
		@course = Course.where(:course_name => courseName).first
		if !@course
			flash[:notice] = "This course is not held in this quarter. Misspell anything? Or you can <a href='/newbook'>submit a request</a> for this new book.".html_safe
			return redirect_to(root_url)
		end
	else
		redirect_to(root_url)
	end
  end

  def show
	if params[:book].present? && !params[:book].blank?
		@book = Book.where(:book_title => params[:book].strip).includes("msgcount").order("msgcounts.last_update DESC")
		@bookinfo = Bookinfo.where(:book_title => params[:book].strip).first
		if !@bookinfo
			flash[:notice] = "The book does not exist."
			return redirect_to(root_url)
		end
	else
		redirect_to(root_url)
	end
  end

  def postto
	if params[:book].present? && !params[:book].blank? && params[:from].present? && !params[:from].blank? && (params[:from].strip == 'find' || params[:from].strip == 'show')
		bookname = params[:book].strip
		#if book in bookinfo
		binfo = Bookinfo.where(:book_title => bookname).first
		if binfo
			bk = Book.where(:username => current_user.username, :book_title => bookname).first
			if bk
				flash[:notice] = "You have already posted the book"
				if params[:from].strip == 'find'
					return redirect_to('/find?coursename=' + binfo.course_name.split(',').first)
				else
					return redirect_to('/show?book=' + bookname)
				end
			else
				#increment bookinfo
				binfo.number = binfo.number + 1
				if binfo.save
					#if user have traded the book, resume
					tb = Tradedbook.where(:username => current_user.username, :book_title => bookname).first
					if tb
						tb.destroy
					end
					#add to book
					Book.create(:book_title => bookname, :username => current_user.username)

					#add to owned
					Ownedbook.create(:book_title => bookname, :username => current_user.username)
					flash[:notice] = bookname + " is posted successfully"
					if params[:from].strip == 'find'
						return redirect_to('/find?coursename=' + binfo.course_name.split(',').first)
					else
						return redirect_to('/show?book=' + bookname)
					end
				end
			end
		end
	end
	redirect_to(root_url)
  end
end

UWTextbookExchange/app/helpers/get_book_helper.rb
module GetBookHelper
end

UWTextbookExchange/app/views/get_book/find.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Hustees</title>
	<link href="//netdna.bootstrapcdn.com/bootswatch/3.1.1/simplex/bootstrap.min.css" rel="stylesheet">
	<%= stylesheet_link_tag('commonbg', :media => 'all') %>
	<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
	<%= csrf_meta_tags %>
<style>
body {
	min-width: 768px;
}

h2 {
	margin-top: 5px;
}
.bookresult {
	margin: 10px;
	clear:both;
}
.postlink {
	font-size: 1.2em;
	padding-left: 5px;
	vertical-align: middle;
	font-weight: bold;
}

.notice {
	margin-bottom: 10px;
	border-radius: 5px;
	padding: 5px;
	border: 1px red solid;
	background-color: #ff9999;
	text-align: center;
	color: black;
	font-weight: bold;
}
#result {
	color:rgb(68, 68, 68);
	margin-top: 10%;
}

.bookresult a {
	color: rgb(29, 67, 168);
}
</style>
</head>

<body>
	<%= render template: "layouts/bar" %>

	<div class="main" style="width:90%;margin:auto">

		<h1 id="result">Search Result for <%= @course.course_name %></h1>

		<% if !flash[:notice].blank? %>
			<div class = "notice">
				<%= flash[:notice] %>
			</div>
		<% end %>
		<% if !user_signed_in? %>
			<div>Sign in to post</div>
		<% end %>
		<% @course.attributes.each do |attr_name, attr_value| %>
			<% if attr_name != "id" && attr_name != "course_name" && attr_name != "number" && attr_value != nil %>
				<div class="bookresult">
					<a href="<%=root_url%>show?book=<%=attr_value%>"><%=attr_value%></a>
					<% if user_signed_in? %>
						<span class="postlink"><a href="<%=root_url%>postto?from=find&book=<%=attr_value%>">Post</a></span>
					<% end %>
				</div>
			<% end %>
		<% end %>
	</div>
	<%= render template: "layouts/foot" %>
</body>
</html>

UWTextbookExchange/app/views/get_book/read.html.erb
<h1>Search Result</h1>
<% @courseInfo.attributes.each do |attr_name, attr_value| %>
  <% if attr_name != "id" && attr_name != "created_at" && attr_name != "updated_at" && attr_value != nil %>
    <div>
      <%= attr_name %>: <%= attr_value %>
    </div>
  <% end %>
<% end %>

UWTextbookExchange/app/views/get_book/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Hustees</title>
	<link href="//netdna.bootstrapcdn.com/bootswatch/3.1.1/simplex/bootstrap.min.css" rel="stylesheet">
	<%= stylesheet_link_tag('commonbg', :media => 'all') %>
	<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
	<%= csrf_meta_tags %>
<style>
h2, h3 {
	margin-top: 60px;
	margin-bottom: 5px;
	padding-left: 5px;
	color:orange;
}
.postlink {
	font-size: 1.2em;
	padding: 5px;
	vertical-align: middle;
	font-weight: bold;
}
.option {
	margin: 10px;
	clear:both;
	color:grey;
}
.users {
	margin: 5px;
	float: left;
	padding-right: 10px;
}
.notice {
	margin-bottom: 10px;
	border-radius: 5px;
	padding: 5px;
	border: 1px red solid;
	background-color: #ff9999;
	text-align: center;
	color: black;
	font-weight: bold;
}
div>a {
	color: orange;
}
</style>
<style type="text/css" id="_om_css_global">._om_hidden {
	visibility: hidden;
}</style><style type="text/css" id="_om_css_twenga">._om_twenga_widget {
	text-align: left;
	box-sizing: border-box;
	background-color: white;
	display: none;
}

._om_twenga_widget_header strong {
	font-weight: 700;
}

._om_twenga_widget_viewport {
	overflow: hidden;
	white-space: nowrap;
	width: 100%;
	height: 100%;
}
._om_twenga_widget_viewport_container {
	position: relative;
	text-align: center;
}

.vertical ._om_twenga_widget_viewport {
	overflow: hidden;
	white-space: normal;
}

._om_twenga_back_arrow {
	z-index: 10;
	display: none;
	border: none;
	cursor: pointer;
	position: absolute;
	right: 100%;
	top: 50%;
	margin-top: -24px;
}

.vertical ._om_twenga_back_arrow {
	top: inherit;
	right: inherit;
	left: 50%;
	bottom: 100%;
	margin-left: -24px;
	margin-top: 0;
}

._om_twenga_forward_arrow {
	z-index: 10;
	display: none;
	border: none;
	cursor: pointer;
	position: absolute;
	left: 100%;
	top: 50%;
	margin-top: -24px;
}

.vertical ._om_twenga_forward_arrow {
	left: 50%;
	top: 100%;
	margin-left: -24px;
	margin-top: 0;
}

body._om_twenga_tb_visible #Body {
	margin-top: 37px !important;
}

body._om_twenga_tb_visible #gb {
	top: 37px;
}

._om_widget_product > table {
	border: none;
	border-collapse: collapse;
	border-spacing: 0;
	cursor: pointer;
	text-align: center;
	display: table;
	margin: 10px;
	width: 100px !important;
}

._om_widget_product tr {
	vertical-align: middle !important;
}

._om_widget_product td {
	vertical-align: inherit !important;
}

._om_twenga_price {
	display: block;
	font-size: 11px;
	width: 100px;
	overflow: hidden;
	text-overflow: ellipsis;
	height: 16px;
	white-space: nowrap;
	font-weight: normal;
}

._om_widget_product_image {
	max-width: 100px;
	max-height: 100px;
}

._om_widget_merchant_logo_domain {
	height: 28px;
	display: block;
	width: 100px;
	text-overflow: ellipsis;
	overflow: hidden;
	white-space: nowrap;
}

._om_widget_merchant_logo_domain > a {
	color: green;
	text-overflow: ellipsis;
	overflow: hidden;
	text-decoration: none;
	white-space: nowrap;
}

._om_widget_merchant_logo_image {
	text-align: center;
	display: block;
	min-height: 28px;
}

</style>
</head>

<body>
	<%= render template: "layouts/bar" %>
	<div class="main" style="width:90%;margin:auto">
		<h2>Details</h2>
		<% if !flash[:notice].blank? %>
			<div class = "notice">
				<%= flash[:notice] %>
			</div>
		<% end %>
		<% if @bookinfo.number > 0 %>
			<div class="option">Name: <%=@bookinfo.book_title %></div>
			<div class="option">Author: <%=@bookinfo.author %></div>
			<div class="option">
				<% if @bookinfo.course_name.split(',').count > 1 %>
					Courses: 
				<% else %>
					Course:
				<% end %>

				<% @bookinfo.course_name.split(',').each do |course| %>
					<a href="<%=root_url%>find?coursename=<%=course%>"><%=course%></a>
				<% end %>
			</div>
			<% if user_signed_in? %>
				<div class="postlink"><a href="<%=root_url%>postto?from=show&book=<%=@bookinfo.book_title%>">Post</a></div>
			<% else %>
				<div class="postlink"><%=link_to('Sign in', new_session_path(resource_name)) %> to post this book</div>
			<% end %>
			<% if @bookinfo.number == 1 %>
				<% has = 'has' %>
			<% else %>
				<% has = 'have' %>
			<% end %>
					<h3><%= pluralize(@bookinfo.number, 'person') %> <%= has %> the book</h3>
			<% if user_signed_in? %>
				<span class="users">
					<% @book.each do |bk| %>
						<% if bk.username != current_user.username%>
							<% if bk.msgcount.last_update > 2.minutes.ago %>
								<%= image_tag('online.png', size:"12x12") %>
							<% else %>
								<%= image_tag('offline.png', size:"12x12") %>
							<% end %>
							<a href="<%=root_url%>chat?receiver=<%=bk.username%>"><%=bk.username%></a>
						<% end %>			
					<% end %>
				</span>
			<% else %>
				<div><%=link_to('Sign in', new_session_path(resource_name)) %> or <%=link_to('Sign up', new_registration_path(resource_name)) %> to see who has it.</div>
			<% end %>
		<% else %>
			<div class="option">Name: <%=@bookinfo.book_title %></div>
			<div class="option">Author: <%=@bookinfo.author %></div>
			<div class="option">Price: <%=@bookinfo.price %></div>
			<div>Sorry, no one has posted this book yet.</div>
			<% if !user_signed_in? %>
				<div><%=link_to('Sign in', new_session_path(resource_name)) %> or <%=link_to('Sign up', new_registration_path(resource_name)) %> to post it.</div>
			<% else %>
				<div>Do you want to <a href="<%=root_url%>postto?book=<%=@bookinfo.book_title%>">post</a> it?</div>
			<% end %>
		<% end %>
	</div>
	<%= render template: "layouts/foot" %>
</body>
</html>